### ISSUE TITLE
update Google Cloud API client import paths and more

### ISSUE THREAD

**Issue by jba** [root-gg/plik#170]
The Google Cloud API client libraries for Go are making some breaking changes:
- The import paths are changing from `google.golang.org/cloud/...` to
  `cloud.google.com/go/...`. For example, if your code imports the BigQuery client
  it currently reads
  `import "google.golang.org/cloud/bigquery"`
  It should be changed to
  `import "cloud.google.com/go/bigquery"`
- Client options are also moving, from `google.golang.org/cloud` to
  `google.golang.org/api/option`. Two have also been renamed:
  - `WithBaseGRPC` is now `WithGRPCConn`
  - `WithBaseHTTP` is now `WithHTTPClient`
- The `cloud.WithContext` and `cloud.NewContext` methods are gone, as are the
  deprecated pubsub and container functions that required them. Use the `Client`
  methods of these packages instead.

You should make these changes before September 12, 2016, when the packages at
`google.golang.org/cloud` will go away.

**Comment by bodji** [comment]
Hi,

Is google.golang.org/api is also concerned ? 

I can't get the  "google.golang.org/api/oauth2/v2" from cloud.google.com.

**Comment by jba** [comment]
There is no such package. Do you mean golang.org/x/oauth2?

**Comment by bodji** [comment]
Are you sure ? 

We are using it there : https://github.com/root-gg/plik/blob/master/server/handlers/google.go#L42

I can go get it : 
`
~ $ go get google.golang.org/api/oauth2/v2
~ $`

**Comment by camathieu** [comment]
> You should make these changes before September 12, 2016, when the packages at
> google.golang.org/cloud will go away.

I assume `google.golang.org/api` is not concerned. 
Since the deadline is due and nothing broke I'm closing this issue.
