### ISSUE TITLE
Auto zipping content

### ISSUE THREAD

**Issue by peperunas** [root-gg/plik#175]
Is it possible to implement an auto-zipping feature? It would be great to zip multiple files server side. (Great for mobile phones uploading pictures)

**Comment by camathieu** [comment]
Indeed, I think this is doable on download.

**Comment by bodji** [comment]
It's done in 1.2 branch :) (soon merged in master)

Commit : https://github.com/root-gg/plik/commit/04d2f681001479ae7251ae4c33c512f44e4cde95

**Comment by peperunas** [comment]
Wow that was fast! Thanks!

**Comment by peperunas** [comment]
Sorry if I comment again, is it possible to update the docker image (on the Docker Hub) too? Thanks!

**Comment by bodji** [comment]
It will be done when we release final version of 1.2 :)

**Comment by camathieu** [comment]
I've pushed root-gg/plik:dev to Docker Hub. The image inlude the 1.2 latest patches.

**Comment by peperunas** [comment]
I've pulled the `dev` image but once the files are uploaded I can't see any "Create zip" (or similar" feature. Am I missing something?

**Comment by camathieu** [comment]
I made the last patch by editing a file on github and built the image to try that patch which was made apparently made against 1.2-RC1, I'm rebuilding the image.

**Comment by camathieu** [comment]
Done.

I had to refresh my browser's cache to get the Zip archive button.
https://plik.root.gg/file/6qmp1nCrc1bqFjtt/9b6Iij3l67Nof0th/2016-12-20-213906_1429x1041_scrot.png

You should see this if you curl /version :

    "date": 1482265576,
    "gitFullRevision": "c3eb074e8da33f57853d8a022263fad9a0f2abb1",
    "gitShortRevision": "c3eb074",
    "goVersion": "go1.7.4 linux/amd64",
    "host": "ks2.root.gg",
    "isMint": true,
    "isRelease": false,
    "user": "root",
    "version": "1.2-RC3"

**Comment by peperunas** [comment]
Unfortunately, it isn't working for me. I've updated the image (pulled from the Docker Hub) but nothing.
Tried with several devices + incognito mode.

**Comment by camathieu** [comment]
I've tested to pull rootgg/plik:dev from docker hub on my local machine and it worked.
I think you are still pulling rootgg/plik:latest

root@Legendary:/home/skatkatt# docker pull rootgg/plik:dev
dev: Pulling from rootgg/plik
da7969a02804: Pull complete 
b19ed54e5d59: Pull complete 
bee040a735c4: Pull complete 
54e91ff403be: Pull complete 
b07b228eba5e: Pull complete 
b64e0633c583: Pull complete 
a6ffe6d98926: Pull complete 
e4f1b6263155: Pull complete 
be81789a8a72: Pull complete 
e9dc958b70df: Pull complete 
de25b6c33ef6: Pull complete 
e7b449d4ec4c: Already exists 
cb6fb082434e: Already exists 
d4b2ba78e3b4: Already exists 
Digest: sha256:676170e7de2d895ae4e0ec1d9ca9fd990efcc5190b10493ce6be5477b613df5f

Status: Downloaded newer image for rootgg/plik:dev
root@Legendary:/home/skatkatt# docker run -p 8081:8080 rootgg/plik:dev
[12/20/2016 20:56:20][INFO    ] Starting plikd server v1.2-RC3
[12/20/2016 20:56:20][INFO    ] Starting http server at http://0.0.0.0:8080
[12/20/2016 20:56:20][INFO    ] Will clean old uploads in 8247 seconds.

**Comment by peperunas** [comment]
Something is not right on my end then. I'm using your same image. Different results though.
```
Pulling transfer (rootgg/plik:dev)...
dev: Pulling from rootgg/plik
81cc5f26a6a0: Already exists
a3ed95caeb02: Already exists
a8926a85eb8c: Already exists
484a4e83bafa: Already exists
3ee63697a8c2: Already exists
122f924e9fa9: Already exists
ce3061537e4d: Already exists
Digest: sha256:676170e7de2d895ae4e0ec1d9ca9fd990efcc5190b10493ce6be5477b613df5f
Status: Image is up to date for rootgg/plik:dev
```

**Comment by peperunas** [comment]
I'm sorry if I insist but I've been trying for more than 1 hour.. still nothing.

I've cleaned every cache imaginable on my server! Have you got any tips?

**Comment by camathieu** [comment]
Checking

**Comment by camathieu** [comment]
root@Legendary:/home/skatkatt# docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED              VIRTUAL SIZE
rootgg/plik                      dev                 e7b449d4ec4c        2 hours ago          321.8 MB

**Comment by camathieu** [comment]
```
root@ks2:~# docker tag e7b449d4ec4c rootgg/plik:peperunas
root@ks2:~# docker push rootgg/plik:peperunas
The push refers to a repository [rootgg/plik] (len: 1)
e7b449d4ec4c: Image already exists 
de25b6c33ef6: Image already exists 
e9dc958b70df: Image already exists 
be81789a8a72: Image already exists 
e4f1b6263155: Image already exists 
a6ffe6d98926: Image already exists 
b64e0633c583: Image already exists 
b07b228eba5e: Image already exists 
54e91ff403be: Image already exists 
bee040a735c4: Image already exists 
b19ed54e5d59: Image already exists 
da7969a02804: Image already exists 
d4b2ba78e3b4: Image already exists 
cb6fb082434e: Image already exists 
Digest: sha256:963593b054d9a647652494db092b2d7f74ae8bc23841f100add4b1129028eda2

```

**Comment by peperunas** [comment]
It's incredible. Still nothing...
```
Pulling transfer (rootgg/plik:peperunas)...
peperunas: Pulling from rootgg/plik
81cc5f26a6a0: Already exists
a3ed95caeb02: Already exists
a8926a85eb8c: Already exists
484a4e83bafa: Already exists
3ee63697a8c2: Already exists
122f924e9fa9: Already exists
ce3061537e4d: Already exists
Digest: sha256:963593b054d9a647652494db092b2d7f74ae8bc23841f100add4b1129028eda2
Status: Downloaded newer image for rootgg/plik:peperunas
```
```
2b698b53e5e4        rootgg/plik:peperunas     "/bin/sh -c ./plikd"     About a minute ago   Up 19 seconds       0.0.0.0:20000->8080/tcp                            docker_transfer_1
```

```
    "version": "1.2-RC3",
    "date": 1468856213,
    "user": "root",
    "host": "ks2.root.gg",
    "gitShortRevision": "46542f5",
    "gitFullRevision": "46542f538973133794ec15069493ce51390c611f",
    "isRelease": true,
    "isMint": true,
    "goVersion": "go1.5.2 linux/amd64",
```

**Comment by peperunas** [comment]
Solved!

Somehow the old `plikd.cfg` was causing problems!

**Comment by camathieu** [comment]
Glad to hear that :)
