### ISSUE TITLE
Unable to get source IP address

### ISSUE THREAD

**Issue by fgent** [root-gg/plik#176]
Plik installed from root.gg Debian repository. Configured with reverse proxy apache and https. SourceIpHeader fed with server ip. 

While trying to upload, I get 
Oops ! (401)
Unable to get source IP address

[WARNING ][plik.go:850 checkSourceIP][[]] Unable to get source IP address from context

**Comment by fgent** [comment]
Same error without reverse proxy on ip:8080

**Comment by bodji** [comment]
The param SourceIPHeader must have the name of the header containing the ip.

Example : 
`SourceIpHeader      = "X-Forwarded-For" `

**Comment by bodji** [comment]
But we will patch plik to fallback to source ip address 
of the http request if the header is missing or empty.

**Comment by fgent** [comment]
Thanks a lot, it works perfect now !
