### ISSUE TITLE
Google Auth - Error 500

### ISSUE THREAD

**Issue by peperunas** [root-gg/plik#179]
Hello!
I've setup the Google API in Plik but when I do the login, this message pops up:

`Unable to get user info from google API`

What should I do?

Thanks!

**Comment by camathieu** [comment]
Hi, 

Can you look at plik server output or logs to have more insights ?

https://github.com/root-gg/plik/blob/1.2/server/handlers/google.go#L172

The detailed error message can either be : 
- Unable to create google API token : error message
- Unable to create google API client : error message
- Unable to get userinfo from google API : error message

**Comment by camathieu** [comment]
This is the parameters you need to set in your google application in the [Google Developper Console](https://console.developers.google.com) :

https://plik.root.gg/file/03037KAOH5qLB1Nf/ebIOCLr0mh0k5nnN/plik_google_auth.png

and in you plikd.cfg :

Authentication      = true          # Enable authentication
GoogleApiClientID   = "xxxYOUR APP ID HERExxx.apps.googleusercontent.com" # Google api client ID
GoogleApiSecret     = "YOUR APP SECRET HERE" # Google api client secret

I think I can do better with the documentation on this point thanks to pointing that out :
https://github.com/root-gg/plik/blob/master/documentation/api.md

**Comment by peperunas** [comment]
I already did that @camathieu, I think the documentation is okay (the .png is still useful though).
I can't find the logs in the docker image, may you help me find them?

Thanks.

**Comment by camathieu** [comment]
Logs should be displayed when you do a docker run :

cmathieu@cmathieu:~$ docker pull rootgg/plik
Using default tag: latest
latest: Pulling from rootgg/plik

81cc5f26a6a0: Pull complete 
a3ed95caeb02: Pull complete 
475bffcb16ba: Pull complete 
cfe74bb51ec9: Pull complete 
bbebd68f2ef9: Pull complete 
1ea207573871: Pull complete 
Digest: sha256:373368b3864a3aebb168310bc20c8c4a17260656fabf714cd62692b5a45431fe
Status: Downloaded newer image for rootgg/plik:latest

cmathieu@cmathieu:~$ docker run rootgg/plik:latest
[12/20/2016 16:39:42][INFO    ] Starting plikd server v1.2-RC3
[12/20/2016 16:39:42][INFO    ] Starting http server at http://0.0.0.0:8080
[12/20/2016 16:39:42][INFO    ] Will clean old uploads in 10301 seconds.

Are you running the docker image on your local machine ?

**Comment by peperunas** [comment]
Got it:

`Unable to create google API token : Post https://accounts.google.com/o/oauth2/token: x509: failed to load system roots and no roots provided`

**Comment by camathieu** [comment]
I need to add this to the Dockerfile :

RUN apt-get update && apt-get install -y ca-certificates

**Comment by camathieu** [comment]
https://github.com/root-gg/plik/pull/181

**Comment by camathieu** [comment]
I pushed rootgg/plik:dev to docker-hub with the patch. 
Can you confirm that it fix the problem ?

We plan to merge 1.2 to master soon

**Comment by peperunas** [comment]
Works perfectly!
Thanks.
