### ISSUE TITLE
Simplify token feature

### ISSUE THREAD

**Issue by fgent** [root-gg/plik#180]
You could simplify the token creation so that from any authorized ip, a button allows to create a token (a link like https://plik.root.gg/#/?id=NGG5eJiaaK9lGfsc expiring after 24h) which would allow to upload from any ip, and create ONE download link like this : https://plik.root.gg/file/NGG5eJiaaK9lGfsc/LiHJHLalEMLjqHt4/file.zip

Currently it requires a login for permanent upload access. Better one time upload access, without login.
One click to create the access
Still, the link must be created from an authorized ip
Each upload (or set of files) requires a link

**Comment by camathieu** [comment]
That's a very good idea.

We have a concept of upload token to authenticate an upload without the need of a token or account that we can already pass on the URL.

I'm finishing a branch to be able to add files to an existing upload and I think that your feature can fit nicely with that.

**Comment by camathieu** [comment]
https://github.com/camathieu/plik/commit/2bb19c81704c011a859c2900eb3a4bb91d571ac7

Looks good and should be merged soon. I'd like to have your feedback about it.
You can try it live at https://plik.root.gg

**Comment by camathieu** [comment]
The feature is available in the last release https://github.com/root-gg/plik/releases/tag/1.2

**Comment by fgent** [comment]
When empty upload link is created 
/#/?id=Ip9MhsGLr2bEeKe4&uploadToken=66I3IPELLCom9PkL3OHHejKA30ptkP2o

and after one click on “Upload”, I would disable the link (token) and redirect to 
/#/?id=Ip9MhsGLr2bEeKe4

a classic link with both buttons “Add files”, “Delete” and red cross removed.

This way, it locks the token for further use/reuse.

**Comment by fgent** [comment]
From external IP with an empty link, I do not get the 403 but I get an error:
Oops ! (502)
[WARNING ][addFile.go:53 AddFile][[xx.xx.xx.xx][30GPHD4ojcpOnfAF]] Unable to add file from untrusted source IP address
