### ISSUE TITLE
Simplified token error 403/502

### ISSUE THREAD

**Issue by fgent** [root-gg/plik#187]
From external IP with an empty link, I get an error 403 or 502:
Oops ! (502)
[WARNING ][addFile.go:53 AddFile][[xx.xx.xx.xx][30GPHD4ojcpOnfAF]] Unable to add file from untrusted source IP address

**Comment by camathieu** [comment]
Indeed, patch is on the way.

**Comment by fgent** [comment]
Thanks!
I confirm, the change on 1.3-rc1 (#188) makes the trick !
#187 fix add file to upload from untrusted ip with valid upload token
