### ISSUE TITLE
Empty upload feature

### ISSUE THREAD

**Issue by fgent** [root-gg/plik#189]
When empty upload link is created
/#/?id=Ip9MhsGLr2bEeKe4&uploadToken=66I3IPELLCom9PkL3OHHejKA30ptkP2o

and after one click on “Upload”, I would disable the link (token) and (always) redirect to
/#/?id=Ip9MhsGLr2bEeKe4

a classic link with both buttons “Add files”, “Delete” and red cross removed.

This way, it locks the upload and token for further use/reuse. But any link including an expired/invalid token should always redirect to the shorter one to ensure continuity of the links sent/received. The token dies but the link still points to the uploaded files.
/#/?id=Ip9MhsGLr2bEeKe4&uploadToken=66I3IPELLCom9PkL3OHHejKA30ptkP2o
-> /#/?id=Ip9MhsGLr2bEeKe4

And ideally, enforce a TTL for empty links as a new parameter in plikd.cfg

**Comment by fgent** [comment]
If the token doesn't die after first upload session, like for authorized IPs, it means free reuse until TTL occurs which can become unmanageable with external accesses.

**Comment by camathieu** [comment]
Hi,

Indeed the uploadToken we used to make the create empty upload feature is not something new. It comes from the early drafts of Plik to allow the creator of an upload to add files to it without the need of a complex authentication mechanism.

I understand your need, the feature you want is a more complex and can't be just a html/css trick. We'll have to implement an upload TTL and/or a one shot option ( meaning that only one file can be uploaded ? ).

1.2.1 will be a big cleaning release and in the mean time we are gathering features for 1.3. It will likely be focused on better users management with an admin interface, maybe a local user database (not Google or OVH ), quotas, statistics,... I also believe that creating and managing accounts is true pain-in-the ass so we want Plik to be as full featured as it can be without authentication. Thus your feature definitely fits in nicely.

**Comment by fgent** [comment]
Currently from authorized IP, within the same session we can upload several files, but an F5 or new session removes the "Add files" button. It should be the same using the empty upload link: the token would stay valid under the same session after the first click on 'Upload'. This way several files can be uploaded.
TTL could be typically 1 year, but the empty upload TTL should remain in days, so a dedicated TTL would be useful.
I was thinking about it, Great idea about the admin interface !

**Comment by fgent** [comment]
In the perspective to provide real-time statistics, rethinkdb could be a good option in terms of performance.
