### ISSUE TITLE
"open plik.db: permission denied" after upgrade from 1.2RC to 1.2

### ISSUE THREAD

**Issue by deadbird99** [root-gg/plik#198]
Everything's in the title ;)

Full log message:

> [02/18/2017 12:16:44][INFO    ] Starting plikd server v1.2
> 2017/02/18 12:16:44 Unable to open Bolt database plik.db : open plik.db: permission denied

**Comment by camathieu** [comment]
Looks like a file permission issue.

Could you provide more details about how the upgrade was made ? Are you using the debian package ?
