### ISSUE TITLE
Desktop Client

### ISSUE THREAD

**Issue by maxibanki** [root-gg/plik#199]
Hello,

is there any desktop client available for this upload server?
ShareX is unfortunately not working with this upload server yet.

And thanks for this nice image / file hosting service 👍 👍

**Comment by maxibanki** [comment]
I'm going to add support for sharex. I will reply here as soon as the pr has been agreed.

**Comment by camathieu** [comment]
Wonderful 👍

**Comment by maxibanki** [comment]
I've pulled an it will be accepted and integrated into the next update. You can track the status here https://github.com/ShareX/ShareX/pull/2323.

**Comment by maxibanki** [comment]
Closed, because it will be integrated into the next release.
