### ISSUE TITLE
Need a brief explanation about Plik

### ISSUE THREAD

**Issue by dmxt** [root-gg/plik#202]
I'm technologically literate, I use VPS and I'm not really great at it. I'm primarily a designer, this is the reason why I'm not a primarily a programmer.

Is Plik a service that allow me to run Plik on my VPS, and have ShareX upload files and fetch short url like imgur does, and store files on my server. Is this correct?

Thanks.

**Comment by camathieu** [comment]
Hi,

Yes you can install Plik on your VPS and use it to upload/download files from it. You can try our demo instance at https://plik.root.gg and could get the same result with your VPS with very little effort.

Somebody added Plik as a backend to ShareX not so long ago, you can have more information about it here : https://github.com/root-gg/plik/issues/199.
