### ISSUE TITLE
Support different root path

### ISSUE THREAD

**Issue by peperunas** [root-gg/plik#203]
This would be useful to expose Plik to a reverse proxy such as [Traefik](https://github.com/containous/traefik).

**Comment by ekianjo** [comment]
Actually the other issue I have the the reverse proxy in nginx is linked to that problem: Plik's config file does not support anything else than the / path. Can we have an option to change that setting?

**Comment by camathieu** [comment]
Merged in https://github.com/root-gg/plik/pull/214
