### ISSUE TITLE
Max Days

### ISSUE THREAD

**Issue by Ammar7347** [root-gg/plik#205]
Hi,

I can't seem to increase max days the files will be kept. The max days is 30 days and can't seem to increase it. Any help?

**Comment by bodji** [comment]
In the config file, you can set the default and the max value for TTL : 

`
DefaultTTL          = 2592000       # 30 days
MaxTTL              = 15552000      # 180 days ( 0 => No limit )
`

**Comment by Ammar7347** [comment]
I've tried that before posting and doesn't work unfortrunately.

P.S Do i have to restart VPS in order to changes to apply?

**Comment by bodji** [comment]
You just have to restart plik binary.

How do you launch it ? ( init.d / supervisord / systemd / .... )

**Comment by Ammar7347** [comment]
I am a noob in all this. I use debian 8 and I followed your installation procedure using ./plikd assuming I used init.d :P

**Comment by bodji** [comment]
Launch plikd with -config parameter.

./plikd -config /path/to/config/file.cfg

**Comment by Ammar7347** [comment]
Thanks for the help. I've fixed the issue. In the original config, you have wrote "-1 for no limit" but actually that's not the case. Here you've said 0 for no limit and then restarting the binaries fixed the problem. Thanks again.

**Comment by JayBrown** [comment]
Question: when using the `plik` CLI, can you set the the TTL to forever with the `-t 0` argument? Or do you have to set the `0` in the config file?

I tried uploading with `-t 0`, but it's still set to expire in 30 days.
