### ISSUE TITLE
Debian 9 Stretch Repo ?

### ISSUE THREAD

**Issue by martintamare** [root-gg/plik#209]
Do you plan to update the repo to support Debian 9 Stretch ?
Cheers !

**Comment by bodji** [comment]
It's done :)

Last 1.2 release has been pushed.

**Comment by martintamare** [comment]
👍

**Comment by martintamare** [comment]
After testing : http://mir.root.gg/dists/ :(

**Comment by martintamare** [comment]
Petit up ?

**Comment by martintamare** [comment]
Any news ? :)

**Comment by martintamare** [comment]
Any news for http://mir.root.gg/dists/stretch ?

**Comment by bodji** [comment]
Hey !

It's done :)

Sorry for the delay. See you soon :)

**Comment by martintamare** [comment]
Thx !

**Comment by martintamare** [comment]
Hello again :)
Only plik is available, not plikd :(
