### ISSUE TITLE
[Content] Grammatically incorrect sentence formation

### ISSUE THREAD

**Issue by checkaayush** [root-gg/plik#211]
![screenshot from 2017-08-31 16-13-00](https://user-images.githubusercontent.com/4137581/29919520-504420d0-8e67-11e7-9072-10c645f2a6d9.png)

Could instead be `This upload will expire on <data> at <time>`

**Comment by camathieu** [comment]
Thank you for noticing that.

**Comment by camathieu** [comment]
Merged in https://github.com/root-gg/plik/pull/214
