### ISSUE TITLE
 Add shorten URL flag to the plik CLI

### ISSUE THREAD

**Issue by damajor** [root-gg/plik#212]
Hi,

I just noticed that the plik CLI does not include the URL shortening.
It could be great and priceless to add it :)

Cheers,
damajor

**Comment by camathieu** [comment]
Good catch, we currently have an open discussion about shortlinks as we don't really like the way it works for now.
https://github.com/root-gg/plik/issues/185

**Comment by camathieu** [comment]
I think we even go further and removed the feature as we didn't thought it matched our requirements.
https://github.com/root-gg/plik/commit/bb8c9151cdf9c4180f5e19b1d6d992a8de44593b

**Comment by damajor** [comment]
Ok
I wrote some comment on #185
