### ISSUE TITLE
Plik CLI admin

### ISSUE THREAD

**Issue by damajor** [root-gg/plik#213]
Hi,

Maybe I did not find the correct information but it could be nice to have a CLI to administrate the server, for example:

plikadm list files
plikadm delete [id]

**Comment by camathieu** [comment]
Indeed that would be great.

But there is no API to do such things for now. 
In fact this is the roadmap of the next release.
Admin API / UI / CLI would be pretty neat isn't it :)

That means quite a bit of work to be done nicely though and the bad news is that we don't expect to have much time to work on that before the winter.
Any help would be welcome.
