### ISSUE TITLE
Improve Content Security Policy

### ISSUE THREAD

**Issue by mxschmitt** [root-gg/plik#233]
When you use [csp-evaluator.withgoogle.com](https://csp-evaluator.withgoogle.com) to check the Content Security Policy there appear errors in the `plugin-types` and `sandbox section`.

Additional there should be allowed to play a `mp4` file in the browser instead of getting the following error:
![image](https://user-images.githubusercontent.com/17984549/33269487-2f9d6c10-d381-11e7-9b93-7dbe44bba984.png)
I can be simply reproduced by uploading a `mp4` file. (In my case I used ShareX with the Plik uploader).

**Comment by carsso** [comment]
We have the same issue with `.pdf` files.

**Comment by maxibanki** [comment]
I've created an PR for fixing the mp4 issue (#234). Also I tried to reproduce the PDF one, but the PDF will be always downloaded directly instead of getting the inline view displayed.

**Comment by camathieu** [comment]
This header works as expected, it is here to avoid loading resources and plugins, especially from Adobe,  to protect the domain and the users from a wide range of attacks and I'd like to be able to keep those values for certain sensitive deployments. But I admit that this can be too paranoïd for certain use cases.
What do you guys think about a "WebSecurityLevel" => DEFAULT/PARANOID.

For pdfs / flash content we are forcing them to application/octect-stream to force the download a few lines before the  Content-Security-Policy header : https://github.com/root-gg/plik/blob/8c1792d486729c6b8de43ab0f228214dae2a0d14/server/handlers/getFile.go#L99

With PARANOID being : 
"default-src 'none'; script-src 'none'; style-src 'none'; img-src 'none'; connect-src 'none'; font-src 'none'; object-src 'none'; media-src 'none'; child-src 'none'; form-action 'none'; frame-ancestors 'none'; plugin-types ''; sandbox ''"
NO HTML / NO FLASH / NO PDF / ...

With DEFAULT :
"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'self'; font-src 'self'; object-src 'self'; media-src 'self'; child-src 'self'; form-action 'self'; frame-ancestors 'self';
NO HTML / NO FLASH

And maybe even NONE (?) :
no Content-Security-Policy header
HTML / FLASH / allowed

**Comment by maxibanki** [comment]
This could be a better solution. But I think we should allow mp4 files e.g.?
And what do you think about that the [csp-evaluator.withgoogle.com](https://csp-evaluator.withgoogle.com) says that `plugin-type` and `sandbox` is an invalid value when they are empty?

**Comment by camathieu** [comment]
Yes, it looks like it should be 'none'.

From the scp-evaluator :
script-src 'self' can be problematic if you host JSONP, Angular or user uploaded files.

I'm trying to find appropriates values to play most plugins

**Comment by camathieu** [comment]
The good thing is that to play mp3/mp4 files I only need to add media-src self.

**Comment by camathieu** [comment]
There will be a new setting to disable the security headers in 1.3

**Comment by camathieu** [comment]
Hello, we have released 1.3-RC.

There is now a configuration parameter to disable those HTTP security headers ( https://github.com/root-gg/plik/blob/master/server/plikd.cfg#L28 )

Hope it will fit your needs. Any feedback would be much appreciated.
