### ISSUE TITLE
Unable to retrieve file if password is set and plik is behind apache : Missing Authorization header

### ISSUE THREAD

**Issue by meepmeep** [root-gg/plik#242]
Hi

I set up plik behind apache with this configuration : 
        ProxyPass /  http://127.0.0.1:8080/
        ProxyPreserveHost On
        ProxyRequests on

I can upload files and download them, but if I want to set a password, when I try to retrieve the file I get this message : 
`{"message":"Please provide valid credentials to access this upload","value":null}
`

In logs : 
`[02/02/2018 12:06:10][WARNING ][[127.0.0.1][srsUkD1ili00savw]] Missing Authorization header`

I'm using the git version on debian (tar.gz version doesn't work at all .. but this will be another issue ;))

**Comment by camathieu** [comment]
Hello I’ve tried to reproduce your issue without success :

Apache 2.4.29-2 with this vhost configuration :

<VirtualHost *:8888>
	ProxyPass / http://127.0.0.1:8080/
	ProxyPreserveHost On
	ProxyRequests on
</VirtualHost>

Plik server is built from the last master commit and run with the default configuration :

curl http://127.0.0.1:8888/version <http://127.0.0.1:8888/version> :
"version":”1.2.2"
"gitShortRevision":”8c2400a"
"gitFullRevision":”8c2400aabb9897e52cb41817c6a8a61ffe475a75"
"isRelease”:false
"isMint”:true
"goVersion":"go1.7.4 linux/amd64"

Uploading a file protected by user/password just went fine and downloading it from private browsing mode went just fine.
The header seems to be totally missing, can you check with the developper web console that the header is actually being sent by the browser ?

**Comment by meepmeep** [comment]
Ouch. 
Indeed, I completely forgot that I was  on corporate network, which has a really strange behaviour with http-auth (not prompting htaccess / auth popup)
Sorry for this useless issue :)
