### ISSUE TITLE
plik API client in c# for net45 and netstandard2.0 

### ISSUE THREAD

**Issue by iss0** [root-gg/plik#246]
Hey there,

I've written a client for the great plik API. Maybe it helps people writing apps leveraging the power of plik.
Thanks for your great work! The repo is [plikSharp](https://github.com/iss0/plikSharp).

Best, Jan

**Comment by camathieu** [comment]
:+1:

**Comment by camathieu** [comment]
I've updated the main README.
Thank you very much for your work and consideration. :)
