### ISSUE TITLE
Unclear config file documentation

### ISSUE THREAD

**Issue by rhass** [root-gg/plik#248]
There is a few things which are unclear in the inline documentation of the example config file:

1. `YubikeyAPIKey` -- When you request a key, there is a numeric "Client ID" and a secret key. I am assuming this value is supposed to be the Client ID, but it is not clear.
1. `UploadWhiteList` -- Does this use CIDR notation, or a range such as: `1.1.1.0-1.1.1.254`

**Comment by camathieu** [comment]
Hello, 

Sorry I missed your issue.

1 . Yes you're right this field should contain a numerical ID that you need to declare as a string though.
2 . UploadWhiteList can use Single IP or CIDR notation.

I'm updating the config file sample
