### ISSUE TITLE
Get API key for custom uploader in ShareX

### ISSUE THREAD

**Issue by MAGICCC** [root-gg/plik#252]
Hello,

I installed plik on my box using the docker container,  but I want to use it as custom uploader in my ShareX instance.
I got the application key and the secret application key from the OVH page, put them in my config and did a `docker-compose down && docker-compose up -d`. When I enter either the application key or the secret application key in my ShareX setting as API Key it doesn't work. (`{"message":"Invalid token","value":null}`) I guess it's another key I need, but how to get it?

Thanks

**Comment by camathieu** [comment]
I've never used the ShareX upload but I guess that it is has the same behavior as the Plik command line client.

First you need to start your plik server with the authentication setup with OVH or Google.

Then you need to go to your plik server and use the authentication feature to login into your plik server using your OVH or Google credentials.

This will give you access to your plik account page. Here you can Vue your uploads and create plik Tokens that can be used to authenticate the plik command line client and I guess the ShareX client as well.

Do not hesitate to ask for more information if this is not clear of does not work.

**Comment by MAGICCC** [comment]
Oh thanks. 
I didnt see the Authentication button on the page :/
