### ISSUE TITLE
Bolt backend not maintained anymore

### ISSUE THREAD

**Issue by duckie** [root-gg/plik#259]
Hello there

It appears that the bolt project have been archived: https://github.com/boltdb/bolt.

What is the plan for Plik ? Is the MongoDB backend the only maintained one ? Or can we still use the file backend for public instances ?

**Comment by camathieu** [comment]
Hello,

Good point, that's something we are aware of. We should consider migrating at least to https://github.com/etcd-io/bbolt for the next 1.x releases if it's kind of a drop-in replacement.

The long terms plans for plik would be to rely on something more high level than bolt to painlessly build some kind of admin dashboard. Supporting only MongoDB could be an option but we also really love the wget -> ./plikd style of standalone deployment. So we would need to review what are the available alternatives for persisting metadata, maintaining multiple backends for this is also a pain so if we could find something that could easily work for standalone and HA deployment that would be great.

**Comment by camathieu** [comment]
Removed in 1.3
