### ISSUE TITLE
swift - specify region

### ISSUE THREAD

**Issue by MV1908** [root-gg/plik#261]
Hi,

It would be nice to be able to specify in which openstack region the container is stored.

when using OVH openstack swift as backend, the upload is stored in poland (the plik container is created there if it does not exist), and I would like the data to be stored in France.

**Comment by vialou** [comment]
Hi @MV1908 how did you configure plik with an OVH openstack swift ?
Could you please share your plikd.cfg parameters for [DataBackendConfig] ?

**Comment by camathieu** [comment]
https://github.com/root-gg/plik/issues/289
