### ISSUE TITLE
default settings

### ISSUE THREAD

**Issue by renard** [root-gg/plik#264]
Is there a way (better in the configuration file than the code) to force some options while uploading a file?
For example I need all my uploaded files to have a password.

I have done it this way but I having in the configuration file is way better.

```patch
@@ -402,7 +402,7 @@
         $scope.upload = {};
         $scope.files = [];
         $scope.yubikey = false;
-        $scope.password = false;
+        $scope.password = true;

         // Get server config
         $config.getConfig()
```

Thanks

**Comment by camathieu** [comment]
This will be possible in 1.3.6 once this PR is merged : https://github.com/root-gg/plik/pull/434

**Comment by camathieu** [comment]
Released in https://github.com/root-gg/plik/releases/tag/1.3.6
