### ISSUE TITLE
Add S3 support

### ISSUE THREAD

**Issue by pandruszkow** [root-gg/plik#270]
Hi guys,

I've been looking at a bunch of different image uploaders for my use case, and it seems like Plik is the closest thing to what I'm looking for. S3 support would make it a near-exact match.

S3 is basically a lingua franca for object storage from what I've seen. With no extra effort, it would allow:
 - connecting Plik to S3 and cheaper alternatives (like Wasabi)
 - self-hosted S3-compatible file servers (such as [Minio](https://min.io))
 - indirectly connecting to Azure and Google Cloud Storage (GCS) using Minio's gateway mode

Is there any chance that this could be added, if it's not too much work? I know that OpenStack Swift is supported as a backend, but OpenStack has a bit of a learning curve when setting up (and it's a bit heavy-weight in terms of resource use too).

**Comment by kylesmith63** [comment]
Would love to see this also

**Comment by camathieu** [comment]
Hello,

I'll take a look and let you know.

Thanks for your interest.
CAM.

**Comment by camathieu** [comment]
Hello, we have released 1.3-RC.

You can now use S3 as a data backend

Hope it will fit your needs. Any feedback would be much appreciated.
