### ISSUE TITLE
How to change default login user 'plik' to another like 'admin'?

### ISSUE THREAD

**Issue by m2acgi** [root-gg/plik#271]
How to change default login user `plik` to another like `admin`?

**Comment by camathieu** [comment]
Hello,

I think that we can easily add a configuration switch.

https://github.com/root-gg/plik/blob/master/server/handlers/createUpload.go#L165

**Comment by camathieu** [comment]
Default user has been changed to `user` in https://github.com/root-gg/plik/commit/e3a35a21693fbc0cddf1806774663dc4de66f2e6

**Comment by camathieu** [comment]
Released in https://github.com/root-gg/plik/releases/tag/1.3.6
