### ISSUE TITLE
simple authentication

### ISSUE THREAD

**Issue by aravindhsampath** [root-gg/plik#273]
Hi. 

plik seems like a really nice projects that does almost exactly what I would like for it to do. Cheers on such a nice open source project! 

The only reason I cannot roll this out to my research group users is because of the lack of simple authentication mechanism. I cannot direct my users to Google/OVH. I wish there was a simple username/password authentication I can require by default from anybody who visits the homepage and trying to upload anything.  Is it possible to add such a feature? 

LDAP integration would be super nice, but I see an issue created for it already and it might be more complicated than what I need anyway.

**Comment by Vastrix** [comment]
Indeed, Even a simple **API token/auth feature** would be awesome! No third party authenticators..
*p.s.: Why is OVH even an option? aren't they a server provider?*

**Comment by camathieu** [comment]
https://github.com/root-gg/plik/issues/279

**Comment by camathieu** [comment]
Hello,

Sorry for the late reply.
We'll try figure a way for 1.3. This should be doable with the current user/token framework. We just need a way to manipulate ( create/list/remove ) static users that are not tied to google/ovh

Why is OVH even an option? aren't they a server provider ? => It was developed at OVH.

**Comment by camathieu** [comment]
Hello, we have released 1.3-RC.

You can now disable the web UI from the configuration ( https://github.com/root-gg/plik/blob/master/server/plikd.cfg#L26 )

And you can create local users from the server binary.

Hope it will fit your needs. Any feedback would be much appreciated.
