### ISSUE TITLE
Streaming DOES upload to server?

### ISSUE THREAD

**Issue by Vastrix** [root-gg/plik#274]
I tested the "streaming" feature on the [site](https://plik.root.gg), however, as soon as I pressed `Upload` it actually started to upload..  
According to the description: `The files will not be stored on the server. Upload will begin when the remote user starts downloading.`  
The upload should begin when the other user has the link/starts downloading, in my case it started uploading immediately (without me giving anyone the download link), indicating that data **does** get stored on the server..?  
  
I figured it might be a buffer (as indicated by: @camathieu in https://github.com/root-gg/plik/issues/216#issuecomment-327025252) however, the progress bar reached 100% (of a 141MB file), indicating that it probably isn't a buffer..
  
soo..?

**Comment by camathieu** [comment]
Hello,

Sorry for the late reply, 

I've already noticed browser going crazy with buffers but 150MB seems high. I'll double check that for 1.3.

**Comment by camathieu** [comment]
I've not been able to reproduce such a behaviour with 1.3-RC1 so I think we are good.
Feel free to reopen if you can reproduce.
