### ISSUE TITLE
Apache proxy with subdirectory?

### ISSUE THREAD

**Issue by gerroon** [root-gg/plik#275]
Hi

Is it possible to serve the Docker image over Apache proxy as a subdirectory as in

`https://DOMAIN/plix`

The examples i saw maps the whole root for plik, which something I would like to avoid if possible.

thanks

**Comment by camathieu** [comment]
Hello,

Sorry for the late reply.

Unfortunately I'm not sure to understand what you intend to do and what the root config parameter is not enough ( or too much ).
