### ISSUE TITLE
Running Plik headless?

### ISSUE THREAD

**Issue by andneuma** [root-gg/plik#278]
Hello,

first of all thanks for providing this great tool as FOSS!

We were wondering if there's any possibility of running this service headless since we only need the API, not the frontend part!? Couldn't find any hints within the config files.

best and thanks a lot in advance!
Andi

**Comment by bodji** [comment]
Hello,

Currently, the frontend is exposed.

We could add a configuration switch to be able to disable it at run time :)

**Comment by andneuma** [comment]
Hello bodji,

that would be nice! Since I'm not into Go at all I wasn't able to find the proper parts in the code to consider. I guess that wouldn't be too much of work for you right?

**Comment by camathieu** [comment]
Hello, we have released 1.3-RC.

You can now disable the web UI from the configuration ( https://github.com/root-gg/plik/blob/master/server/plikd.cfg#L26 )
