### ISSUE TITLE
Limit access

### ISSUE THREAD

**Issue by pr0totyp** [root-gg/plik#279]
Currently we limit the access for uploading files via htaccess to only have the download publicly available. Is there a way to limit parts the api via a shared secret and deactivate the webui for uploading files?

Thanks for this awesome project :)!

**Comment by camathieu** [comment]
Hello,

Sorry for the late reply. 

Adding an option to disable to UI is for sure doable.

For the shared secret part I think that the current implementation of users and tokens already does the job. And we could create a bit of tooling to be able to create/list/remove static users from the cli.

**Comment by pr0totyp** [comment]
No Problem! Thats great news!

How does the current Upload restriction : Source IP / Token work? 
With `UploadWhitelist     = []` i can set ip ranges but how can define a Token restricting uploads?

**Comment by camathieu** [comment]
Today you can create users with Google/OVH api if you setup IP whitelist
then you can create a user (or an unauthenticated upload) only from the
declared IP address range. Then you can create tokens to use with the CLI
client.

What I think would be great is to be able to manage local users. Let's try
first to create an easy manual way to add those users then we might want to
add some mechanism for user registration / validation.

**Comment by camathieu** [comment]
Hello, we have released 1.3-RC.

You can now disable the web UI from the configuration ( https://github.com/root-gg/plik/blob/master/server/plikd.cfg#L26 )

And you can create local users from the server binary.

Hope it will fit your needs. Any feedback would be much appreciated.
