### ISSUE TITLE
Add an interactive token input feature to the CLI

### ISSUE THREAD

**Issue by jle64** [root-gg/plik#280]
Hi,

It would be great if in addition to the `--token` option there was a `--ask-token` or something option to instead read the token from stdin. This would allow inputing the token interactively without it being logged to the shell history or showing up in the process name.

Thanks for the project btw

**Comment by camathieu** [comment]
Would an environment variable be OK?

**Comment by jle64** [comment]
I would prefer a prompt as exporting the variable still gets logged into shell history.

**Comment by camathieu** [comment]
Hello,

In 1.3-RC2 it will be possible to specify "-" as a token value in the .plikrc file or the cli --token argument to ask the client to prompt for user input for token value.

```
➜  client git:(master) ✗ ./plik --token - ../LICENSE 
Token: blah
Unable to create upload : 403 Forbidden : invalid token
```

**Comment by jle64** [comment]
Awesome. Thanks !
