### ISSUE TITLE
Error: missing user, please login first

### ISSUE THREAD

**Issue by Creling** [root-gg/plik#287]
Hello:
Happy to see a simple authentication mechanism in v1.3, however, I meet something wrong when I login via the simple authentication mechanism.

I key in my username/password to get an 'ok'  response in /login and be redirected to /me afterwards.
![图片](https://user-images.githubusercontent.com/43109504/75964012-6f971600-5f01-11ea-8e55-6ccb09db8143.png)

However,  I get an "missing user, please login first" in /me and be redirected to /login again.
![图片](https://user-images.githubusercontent.com/43109504/75964100-95bcb600-5f01-11ea-971e-8d52a6b9d115.png)

**Comment by camathieu** [comment]
Are you using https ?

**Comment by camathieu** [comment]
Why authentication does not work with HTTP connections ?
Plik session cookies have the "secure" flag set, so they can only be transmitted over secure HTTPS connections.

We might want to change that now, or make it optional with the EnhancedWebSecurity parameter

**Comment by camathieu** [comment]
In the mean time you can create self signed certificates and enable SSL directly in plikd.cfg

`openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout plik.key -out plik.crt`

**Comment by Creling** [comment]
it works when I enable SSL, thank you for your help.
maybe we need to update the readme.md

**Comment by camathieu** [comment]
There is a mention of it in the readme in the FAQ part but it's easy to miss.

**Comment by camathieu** [comment]
https://github.com/root-gg/plik/pull/293 has been merged
