### ISSUE TITLE
Can't find AuthVersion in AuthUrl using Swift backend

### ISSUE THREAD

**Issue by jouir** [root-gg/plik#289]
When using "swift" DataBackend and with an OVHcloud configuration like this:
```
[DataBackendConfig]
Username = "***"
Host = "https://auth.cloud.ovh.net/v3/"
ProjectName = "***"
Container = "***"
Password = "***"
```
I have the following error trying to upload files:
```
Mar 07 16:54:45 MASKED.HOSTNAME plikd[3939]: [03/07/2020 16:54:45][INFO    ][[MASKED.IP.ADDR]] POST /upload
Mar 07 16:54:45 MASKED.HOSTNAME plikd[3939]: [03/07/2020 16:54:45][INFO    ][[MASKED.IP.ADDR][MASKED.HASH]] Upload metadata successfully saved
Mar 07 16:54:45 MASKED.HOSTNAME plikd[3939]: [03/07/2020 16:54:45][INFO    ][[MASKED.IP.ADDR]] POST /file/MASKED.HASH/MASKED.HASH/filename.png
Mar 07 16:54:45 MASKED.HOSTNAME plikd[3939]: [03/07/2020 16:54:45][WARNING ][[MASKED.IP.ADDR][MASKED.HASH][MASKED.HASH][filename.png]] Unable to autenticate : Can't find AuthVersion in AuthUrl - set explicitly
Mar 07 16:54:45 MASKED.HOSTNAME plikd[3939]: [03/07/2020 16:54:45][WARNING ][[MASKED.IP.ADDR][MASKED.HASH][MASKED.HASH][filename.png]] Unable to save file : Unable to autenticate : Can't find AuthVersion in AuthUrl - set explicitly
```
Is plik compatible with the openstack auth v3 protocol?

Version:
```
# /usr/share/plik/server/plikd --version
Plik server v1.2.4 (built from git rev 620be7b [mint,release] at 2020-03-01 20:24:57 +0100 CET with go1.11.13 linux/amd64)
```

**Comment by camathieu** [comment]
We built the swift backend a long time ago now, checking.

**Comment by camathieu** [comment]
There are a lot of new possible connection parameters available in the lib so we will now expose them all in the config with their default name in the lib.

I made it work with the following configuration for OVH infra :

```
DataBackend = "swift"
[DataBackendConfig]
       AuthUrl = "https://auth.cloud.ovh.net/v3"
       UserName = "********"
       ApiKey = "***********"
       Domain = "default"
       Container = "test-plik"
```

Feel free to review this :
https://github.com/root-gg/plik/pull/290

To be merge for 1.3-RC2

**Comment by jouir** [comment]
I tested on my own server, no more "AuthUrl" nor "AuthVersion" error anymore.

I still have `internal server error -- Operation forbidden -- 500` errors but it may come from:
* my compilation (make server on go 1.14)
* metadata backend change from `1.2.4` to `1.3` (from file to sqlite3 or postgres)
* server permissions ("plik" user vs "root")

So I need to properly upgrade to the latest version before creating a new unrelated issue because it works on your box.

Thanks for the pull-request!
