### ISSUE TITLE
manage files - Port 9333 not open

### ISSUE THREAD

**Issue by ds2k5** [root-gg/plik#294]
Hello,
how to manage the files ?
The backend Port: 9333 did not open

```
[DataBackendConfig]
Directory = "/var/lib/plik/files"
MasterURL = "http://127.0.0.1:9333"

```

netstat -tulpen | grep 9333   
did not show anything

What do I wrong ?

Thanks

**Comment by camathieu** [comment]
Hello,

I think that you are mixing configuration from different data backends.

If you goal is to save files in the /var/lib/plik/files directory then  you should have the following in your plikd.cfg file ( that you specify with --config cli parameter ) :

```
DataBackend = "file"
[DataBackendConfig]
    Directory = "files"
```

Then the API / WebAPP port is by default 8080 and can be override in the config file https://github.com/root-gg/plik/blob/master/server/plikd.cfg
