### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by tobidwest** [root-gg/plik#299]
Good afternoon,

I am trying to install Plik. However, we're on shared hosting, so I cannot run commands. 

I don't know how to do this manually:
`$ cd plik-1.3-RC1/server
$ ./plikd`

The site loads successfully but uploading does not work because upload.html is missing.

Also, I have some issues with the config file. I checked in the inspector when getting a 404 error on loading, the file "config" was not being found. So, I renamed the file to config because renaming to plikd.conf did not work(?) This resulted in the error message no more appearing but the settings made still are not adopted when opening the site, for instance the default expiration time is not being set.

Thanks for reaching back!

**Comment by camathieu** [comment]
Hello, 

Can you check that the /version or /config http call is working to ensure the webapp is able to reach the backend server ?

**Comment by tobidwest** [comment]
I entered the domain and the window suddenly closed. Now when trying to open plik.exe I can see its window (which only contains a _) but after a short amount of time it is gone.

Windows 64bits

**Comment by tobidwest** [comment]
Excuse me, I'm unsure how to do that. Does using https://reqbin.com/ work? Where do I need to specify the "/version"?
