### ISSUE TITLE
progress bar always show 100%

### ISSUE THREAD

**Issue by riBoon** [root-gg/plik#300]
Like the title says, if there is a upload running, the progressbar always shows 100%. Thats confusing my user.
I use the version 1.3-RC1

Is there a way to fix this?

**Comment by camathieu** [comment]
Hello, 

Can you provide more information about operating system and web browser used, data backend, size of the file you are uploading,...

This is not supposed to happen.

**Comment by camathieu** [comment]
I just tried with Firefox and it seem to always show 0%, there seems to be an issue indeed

**Comment by camathieu** [comment]
To my quick checks it's ok on Chrome / FF / Safari on both Win10 and OSX

**Comment by camathieu** [comment]
Does they progress and block at 100% or go right away to 100% and stay there forever ?

**Comment by riBoon** [comment]
Ok, you're right. I'm using Ubuntu 18.04. firefox and vivaldi (which uses the chrome engine) are ok. 
Strage, its working now in just all browsern. Don't know what changed, on the system where plik runs is nothing changed.

I think, this can be closed until I can reproduce Thanks for your effort (and for this nice tool!)
