### ISSUE TITLE
having trouble logging in with Google (Authentication)

### ISSUE THREAD

**Issue by Dutchglory** [root-gg/plik#301]
having trouble logging in with Google (Authentication)  on the website ( https://plik.root.gg/#/ ) for creating a basic account.  keep getting "internal server error" (500)  ....

**Comment by Lutty76** [comment]
Same here, first login OK but after :+1: 
`(/home/cam/git/go/src/github.com/root-gg/plik/server/metadata/user.go:14) 
[2020-04-08 07:20:19]  UNIQUE constraint failed: users.id 
[04/08/2020 07:20:19][WARNING ][[172.19.0.3]] internal server error -- UNIQUE constraint failed: users.id -- 500
`

**Comment by camathieu** [comment]
Is that a fresh 1.3 install or an upgraded 1.2 db ?

**Comment by Lutty76** [comment]
Fresh install

**Comment by Lutty76** [comment]
For information :



`	
users, _, err  := ctx.GetMetadataBackend().GetUsers(common.ProviderGoogle,false,&common.PagingQuery{})
	for _, item := range users {
		logguer.Info(item.ID) #[04/08/2020 14:33:47][INFO    ][[172.19.0.3]] google:kevin@saagie.com
	}
logguer.Info(common.GetUserID(common.ProviderGoogle, userInfo.Id)) #[04/08/2020 14:33:47][INFO    ][[172.19.0.3]] google:103629477678531485273
`
It's why you doesn't found user in database

**Comment by camathieu** [comment]
Perfect, thank you very much :)
We changed from userInfo.Id to userInfo.Email for 1.3. It made administrating users easier.
