### ISSUE TITLE
rpi3

### ISSUE THREAD

**Issue by luckymedog** [root-gg/plik#305]
Is this supposed to or can it work on a raspberry pi? Including docker images

**Comment by bodji** [comment]
Yes.

If you build the Docker image on your raspberry pi, it will be compiled for the ARM architecture.

And you can also find precompiled versions for all architectures here : https://github.com/root-gg/plik/releases


Kind regards,
Mathieu

**Comment by luckymedog** [comment]
Thank you for your response.

Before I asked the question, I issued command: docker run -t -d --name plikk -p 8080:8080 rootgg/plik
 and container exited with "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"



Apr 23, 2020, 07:09 by notifications@github.com:

**Comment by luckymedog** [comment]
and this is what I get when running the binary:

Starting plikd server v1.3-RC1
unable to start Plik server : unable to initialize metadata backend : unable to open database : Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub


Apr 23, 2020, 07:09 by notifications@github.com:

**Comment by Adanteh** [comment]
I use an Odroid HC2 and also can't seem to run it, using the existing docker file gives the exec user, also tried building from the source and dockerfile on the Odroid without any luck, using the binaries I get the same problem as luckymedog's second error.
