### ISSUE TITLE
docker container exit error

### ISSUE THREAD

**Issue by luckymedog** [root-gg/plik#307]
When I try running plik via docker on a raspberrypi 3, I get an error:

standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by camathieu** [comment]
I think the Docker image is compiled for x86 and your Raspberry must be running on ARM.

**Comment by hcc23** [comment]
I am facing the exact same issue (although trying to run plik on a raspberrypi 4):

The image provided at https://hub.docker.com/r/rootgg/plik is a `linux/amd64` image, which one can confirm via inspection:

```
root@raspberrypi:~# docker inspect <image ID> | grep Architecture
        "Architecture": "amd64",
```

As  @camathieu noted above, in order for plik to run on a raspberry pi the target architecture needs to be `linux/arm`.

**Comment by hcc23** [comment]
Hi @luckymedog 
I also had this problem and fixed it with a multi-arch image. The respecite PR #319 is linked above. In case you need your image earlier, you can pull the one I created for testing from https://hub.docker.com/repository/docker/hcc23/plik .

**Comment by camathieu** [comment]
Fixed in 1.3

https://hub.docker.com/r/rootgg/plik-linux-arm/tags

**Comment by camathieu** [comment]
Next step :
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by hcc23** [comment]
This is exactly what PR #319 uses - directly in the github actions pipeline.
Thanks for making multi-arch build official :)

**Comment by camathieu** [comment]
We'll definitely be looking into it for 1.4 as a cleaner way to do multi
arch. Thanks for the contribution.
