### ISSUE TITLE
running 1.3 RC1 under Windows with sglite3

### ISSUE THREAD

**Issue by puhlmatz** [root-gg/plik#308]
Are there any description how to do this?
I wasn't able to run the server under Win 10 (1909) with sqllite for Metadatabackend.
Error:
[05/06/2020 09:12:27][INFO    ] Starting plikd server v1.3-RC1
unable to start Plik server : unable to initialize metadata backend : unable to open database : Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

Version 1.23 runs out of the box...?

**Comment by camathieu** [comment]
Windows binaries were removed from the releases for now as it's better than broken.
We'll take a look at how to serup the cross compiling environement for for Windows/Darwin in later releases.
