### ISSUE TITLE
Auth not working in docker

### ISSUE THREAD

**Issue by azurobln** [root-gg/plik#310]
I tried the docker image and was able to create a user but can not log in with credentials. If I do so there is no error message but still get the login-window and can not upload files. If I put wrong credentials or name I get an error, so plik seems to validate data but somehow I am not able to get rights granted.

It would be great if someone can check this and fix. I am using Linux / Fedora with Firefox.

Kind regards,

Martin

**Comment by g33kphr33k** [comment]
I'm having the exact same issue.  It's looking for a /me directory I believe, which doesn't exist:

[06/16/2020 11:24:42][INFO    ][[::1]] POST /auth/local/login
[06/16/2020 11:24:43][INFO    ][[::1]] GET /me

If you go to http://localhost:8080/#/admin you get a Oops ! (401) missing user, please login first.

I'm running from Curl, not docker.

**Comment by camathieu** [comment]
Hello,

Could you provide the plikd.cfg file used to start the server ?

**Comment by f31n** [comment]
For me thats working, but you need to add the user via CLI first.

first get a shell in the running docker container:
docker exec -it plik /bin/bash
* where plik is the name of the docker instance

then run the add user command:
"./plikd --config ./plikd.cfg user create --login userlogin --name username --admin --password password"
