### ISSUE TITLE
Issues running Plik behind Cloudflare as a proxy

### ISSUE THREAD

**Issue by nikwebr** [root-gg/plik#311]
Cloudflare offers to proxy webservers, however, they have an uplod limit of 100 Mb.
Is there a possibility to enable / integrate chunked uploads in plik, so that I am not bound to the Cloudflare upload limit?

Thanks for any suggestions :)

**Comment by savek-cc** [comment]
@QuickTrans no way to contact you directly - but you might want to check your repo for google api keys

**Comment by MichelBaie** [comment]
Can be a good feature to implement to gain access to cloudflare cdn for our files.

**Comment by nikwebr** [comment]
> Can be a good feature to implement to gain access to cloudflare cdn for our files.

No Cloudflare can only serve website related files like html, css and js.

**Comment by MichelBaie** [comment]
But if you use cloudflare to protect yourself from layer7 attacks it can be useful.
