### ISSUE TITLE
Missing downloadDomain in bash script if not given in plikd.cfg

### ISSUE THREAD

**Issue by yellowsoar** [root-gg/plik#314]
While using bash script as client uploading tool:
https://github.com/root-gg/plik/blob/106f7705faa5af2ae09b31be26c3f1ac09f2c4e8/client/plik.sh#L4

If DownloadDomain argument not given in plikd.cfg:
https://github.com/root-gg/plik/blob/106f7705faa5af2ae09b31be26c3f1ac09f2c4e8/server/plikd.cfg#L26

The stdout for **get file** command that generated from `client/plik.sh` will be:
```
curl -s /file/{upload_id}/{file_id}/{file_name} > {file_name}
```

But it is supposed to be something like this:
```
curl -s https://plik.root.gg/file/{upload_id}/{file_id}/{file_name} > {file_name}
```

Ref line for get file command:
https://github.com/root-gg/plik/blob/106f7705faa5af2ae09b31be26c3f1ac09f2c4e8/client/plik.sh#L214

Not sure it's a bug in bash script or a feature in plik?

**Comment by camathieu** [comment]
Fixed in 1.3
