### ISSUE TITLE
feature requst: s3 backend path prefix

### ISSUE THREAD

**Issue by overratedpro** [root-gg/plik#316]
Hi,
First off, great work adding the s3 support! This is a very coveted feature. I would only suggest adding a small improvement - path prefix support. Correct me if I'm wrong, but as of the latest release, plik writes to the root of the bucket.
In our use case we:
- by design do not permit writes to the root of any bucket,
- share buckets between different services.

Having a config option to set a path prefix for the storage in the bucket would really be the selling point.
Thank you!

**Comment by camathieu** [comment]
Implemented in 1.3
