### ISSUE TITLE
Api documentation: XSRF token misspelled

### ISSUE THREAD

**Issue by niclas-lindgren** [root-gg/plik#318]
> To avoid CSRF attacks the value of the plik-xsrf cookie MUST be copied in the X-XRSFToken HTTP header of each authenticated request. 

Should be:

> To avoid CSRF attacks the value of the plik-xsrf cookie MUST be copied in the `X-XSRFToken` HTTP header of each authenticated request.

**Comment by camathieu** [comment]
Fixed in 1.3
