### ISSUE TITLE
UI errors out when default TTL is one day.

### ISSUE THREAD

**Issue by MattDahEpic** [root-gg/plik#321]
This is an edge case in [webapp/js/ctrl/main.js 's getHumanReadableTTL](https://github.com/root-gg/plik/blob/master/webapp/js/ctrl/main.js#L498), which falls through to the default case when the supplied TTL is exactly 86400. It seems to be a one character fix (< to <=) but changing the file in the webapp directory on my instance doesn't get served so I can't test and don't currently have the time to build from source.
![image](https://user-images.githubusercontent.com/7366951/93172546-4e04bb80-f6e8-11ea-90c4-9e49f07a3209.png)

**Comment by camathieu** [comment]
Fixed in 1.3
