### ISSUE TITLE
Add confirm dialog to "Remove" file button

### ISSUE THREAD

**Issue by niclas-lindgren** [root-gg/plik#323]
I see that a confirm dialog was added here #204 .
But as far as I can see there is no confirm dialog when you hit "Remove/X" button?
Maybe I'm using it wrong? But I have accidentally removed files here due to the single click.
Can that be added? 

![image](https://user-images.githubusercontent.com/19908814/94726843-1b042e00-035e-11eb-8e6e-a700c074019a.png)

**Comment by camathieu** [comment]
Nice easy addition.
