### ISSUE TITLE
Google Auth error 400 (incorrect redirect uri) if plik is in a subdirectory

### ISSUE THREAD

**Issue by meepmeep** [root-gg/plik#325]
I just upgrade to 1.3, and everything is working fine.

I wanted to add the google auth but I got this error after clicking on "login with google" 

```
Authorization Error
Error 400: redirect_uri_mismatch
The redirect URI in the request, https://mydomain.ext/auth/google/callback, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}
```

**Which is normal because plik is install on a subdirectory (mydomain.ext/t/)**, so the redirect URI should be https://mydomain.ext/t/auth/google/callback 

I think the "Path" (= "/t/" for me) parameter is not used correctly to define the full qualified url (fqdn + uri).

**Comment by camathieu** [comment]
Good catch.
