### ISSUE TITLE
UploadWhitelist does not work when behind Apache mod_proxy

### ISSUE THREAD

**Issue by msedv** [root-gg/plik#329]
Apache configured as https-Proxy pointing to Plik listening on localhost. When setting our IP range in UploadWhitelist ALL uploads are banned; when setting UploadWhitelist to 127.0.0.1 ALL uploads are allowed (independent from the real location) although Plik recognizes what's going on:

User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
Host: 127.0.0.1:8080
X-Forwarded-For: 192.168.1.4
X-Forwarded-Host: xxx.yyy.net

PS: I love Plik - finally got rid of we** & Co. :-)

**Comment by camathieu** [comment]
To have Plik getting the Source IP from the "X-Frowareded-For" header you should just need to set this in the Plik server configuration ( plikd.cfg ) 

`SourceIpHeader      = "X-Forwarded-For"            # If behind reverse proxy ( ex : X-FORWARDED-FOR )`

https://github.com/root-gg/plik/blob/master/server/plikd.cfg
