### ISSUE TITLE
v1.3 - GLIBC_2.28' not found (required by ./plik/server/plikd)

### ISSUE THREAD

**Issue by EvilBMP** [root-gg/plik#331]
I wanted to try the latest release, but the server executable complaints about the installed glibc version.

`./plik/server/plikd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./plik/server/plikd)`

I checked the GLIBC on my Ubuntu 18.04 LTS via `ldd --version` which results in `ldd (Ubuntu GLIBC 2.27-3ubuntu1.2) 2.27`

Is GLIBC v2.28 for v1.3 of plik really necessary or was the binary only built on a newer CI system?

**Comment by ziuras** [comment]
some question 
but my version is (Debian GLIBC 2.19-18+deb8u10) 2.19

**Comment by camathieu** [comment]
Last binaries were built using Fedora 31 w/ glibc 2.30.

We'll release 1.3.1 using travis CI and and older system version.

**Comment by camathieu** [comment]
This is worse than I thought, in fact the cli client built with `golang:1.15.2-alpine` included in the docker image are linked against `libc.musl-x86_64.so.1` and are not executable on more standard distros.

```
$bash ./plik
./plik: ./plik: cannot execute binary file
$file ./plik
./plik: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, Go BuildID=3a4GrxyDbZK-jqGszyYC/7JQ7dVV6NUcBu_FdfpbW/q7IdfFZ1Jj6kRf5FWpx4/_3nc6pKSCim_4mWRBv3L, not stripped
```
