### ISSUE TITLE
When logging in there is no "Home" button

### ISSUE THREAD

**Issue by pieterhouwen** [root-gg/plik#332]
When using plik with anonymousuploads disabled the user has to login in order to upload.
Couple of things here:

1) Wouldn't it be better to instead of showing an error 400 and have the user manually go to the Authentication page to login use a  redirect which automatically shows the login page showing the error message that the user needs to be logged in to upload files?
2) When the user is logged in there is no way to go back to the home screen without removing the extra parameters in the URL that is hosting plik. Doesn't it make more sense to redirect them to the Home screen once the user is logged in and then have a profile tab in the menu bar? 

![mainmenu-plik](https://user-images.githubusercontent.com/10866686/96242284-96dbb880-0fa3-11eb-96f0-b5527faface3.jpg)

**Comment by camathieu** [comment]
For 2 it's maybe not as obvious as I thought but one can hit the Plik logo

**Comment by camathieu** [comment]
I've checked 1 and it's not as easy to do because of where the error is raised.
We have a refacto of the users planned for 1.4 with email invite/registration we could address that at the same time.

**Comment by camathieu** [comment]
1 has been solve and will be shipped with next version.

**Comment by camathieu** [comment]
![image](https://user-images.githubusercontent.com/6413246/97303579-daafa700-185a-11eb-92c3-a4deff4feed9.png)

I added a "Upload files" link to go back to the main page from the user home page.
