### ISSUE TITLE
Error 413 Request Entity Is Too Large

### ISSUE THREAD

**Issue by pieterhouwen** [root-gg/plik#333]
When uploading a file of ~3MB I get a 413 error message. 
My plik configuration file sets the max upload size to 1GB

my nginx conf:

`
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                # try_files $uri $uri/ =404;
                # proxy_pass http://localhost:8080;
                # proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
#               proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_pass http://localhost:8080;
                proxy_buffering off;
                proxy_request_buffering off;
                proxy_http_version 1.1;
                proxy_buffer_size 1M;
                proxy_buffers 8 1M;
                client_body_buffer_size 1M;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
        }
`

Is this due to the buffer size? If I want to upload a file of 1GB should I set my buffer to that value? Doesn't seem right :)

**Comment by camathieu** [comment]
In general we advise to disable request/response buffering at nginx level

How to disable nginx buffering ?
By default nginx buffers large HTTP requests and reponses to a temporary file. This behaviour leads to unnecessary disk load and slower transfers. This should be turned off (>1.7.12) for /file and /stream paths. You might also want to increase buffers size.

Detailed documentation : http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering

```
proxy_buffering off;
proxy_request_buffering off;
proxy_http_version 1.1;
proxy_buffer_size 1M;
proxy_buffers 8 1M;
client_body_buffer_size 1M;
```

**Comment by pieterhouwen** [comment]
Hi Mathieu,

If you take a look at the nginx config I posted you can see that the directives are already there.
Or do I need to add extra "location" brackets containing above config?

**Comment by gcleaves** [comment]
CDNs limit the max file size so bear that in mind if anybody is behind one.
