### ISSUE TITLE
webapp build process

### ISSUE THREAD

**Issue by freezeboy** [root-gg/plik#336]
When trying to package plik to [nixpkgs](https://github.com/nixos/nixpkgs), I am blocked with the webapp frontend build process

In case you don't know nix, it is a packaging/build system that aims to produce reproducible builds. Therefore, the build tasks are run in a sandbox without netword or implicit dependencies.

I understand that usually, your users just use your docker image, but here I need to perform all the way inside the sandbox.

I use `node2nix` and `bower2nix` to generate the necessary files to pinpoint the dependencies and well it doesn't work today

* Why do you need both npm and bower for a frontend?
* npm looks ok on my side but there is nothing in the build process
* Using node 12 or 14 and grunt 3 generates an error about primordials. It looks like these 3 beast don't mix well.

```
Parsing /.../nixpkgs/pkgs/servers/plik/bower.json failed: ReferenceError: primordials is not defined
```

* Do you have any idea on how to find a working setup for it?
* Is there a source where I can download the dist version of the frontend?

**Comment by camathieu** [comment]
Hi there,

Webapp builds would need some update, bower is now deprecated.

You can get the dist version of the webapp from the release packages I
guess.

Cam.

**Comment by freezeboy** [comment]
Thank you for your answer, I found the webapp content, and it looks good.

Another question, in nix, we try to avoid putting secrets in config files, is there a way to give access to plikd server to the different credentials and tokens outside the plikd.cfg ?

Where can I find the default values (if any) of the config 

Thanks

**Comment by camathieu** [comment]
I understand your conserns about secrets on config file, how would you like to be able to pass them ?
Would env variables be OK ?

**Comment by freezeboy** [comment]
yes

**Comment by freezeboy** [comment]
If I can also ask something else, it would be nice to be able to give the path to the webapp folder (in the config file, or other mean...)

Thank you

**Comment by camathieu** [comment]
I'll create separate issues and close this one.
