### ISSUE TITLE
Cooperation with Security Audit

### ISSUE THREAD

**Issue by andneuma** [root-gg/plik#340]
Dear Plik-Team,

we're using plik as part of our service infrastructure within a middle-sized research institute. We would like to recommend plik to the institute as the central dropping point for onetime file shares. But since we're dealing with quite sensitive data here we would like to perform a security audit (on our costs) first as well as perform some load / stress tests. We have two questions:

a) Would a security audit appreciated by the plik team and would you be willing to implement fixes for possible findings?
b) Furthermore we assume you will appreciate Pull Requests by others, is that correct?

**Comment by camathieu** [comment]
Hello,

we would be delighted to support a security audit of Plik. We are for sure
open to pull requests and collaboration. There is definitely some room
for improvement on this topic.

CAM.

**Comment by andneuma** [comment]
@camathieu thanks for your immediate reply, that sounds awesome. Shall we communicate via this issue or do you have a separate channel that might be more appropriate?

**Comment by camathieu** [comment]
Please contact us by email at cam@root.gg and mathieu@bodjikian.fr.

**Comment by gcleaves** [comment]
Did this initiative make any progress? Can the results be made public?
