### ISSUE TITLE
Plik should allow entry of abuse contact information

### ISSUE THREAD

**Issue by adampankow** [root-gg/plik#341]
The main Plik instance is being used to host malware, but upon visiting the site there did not appear to be any type of information about whom to contact for abuse.

If Plik instances allow public uploading then there should be a place prompting the owner of the instance to enter abuse contact information.

The specific malware I am referencing is hosted at:
hxxps://plik.root.gg/file/w3CUb9UaZ9KIFTCD/SbY2KyreiJUGzbyF/minnne.exe

VirusTotal report:
https://www.virustotal.com/gui/url/3c993455168b067ab98079868e6a949e946afeb32084bfc24a4f183d669a83dc/detection

**Comment by camathieu** [comment]
Good idea, we'll add a field to add an abuse contact in the config and will
remove the file of course.

We do also have plans to integrate with Clam AV.

**Comment by adampankow** [comment]
Awesome! From all us infosec folks, thank you for being so responsive and embracing of security improvements!
