### ISSUE TITLE
Change Background

### ISSUE THREAD

**Issue by PAPAMICA** [root-gg/plik#344]
Hello,

How i can change background ?

I use your docker from docker-hub, I binded a volume to /home/plik/webapp/dist/ and I tried to change "background.jpg" with another png with same name but it doesn't work.
Same when I try  to change style.css.

Can you tell me how can I change this picture please ?
Thanks :)

**Comment by camathieu** [comment]
Hello,

This is the way to go to change the picture in the webapp/dist directory.

CAM.

**Comment by unbelauscht** [comment]
I mounted it readonly as volume:

```
volumes:
                        - ./background.jpg:/home/plik/server/public/img/background.jpg:ro
```
