### ISSUE TITLE
Default .plikrc file

### ISSUE THREAD

**Issue by pieterhouwen** [root-gg/plik#346]
Hello,

Is there a standard template available where all the options that can go into the ~/.plikrc file can go and how to use it when using plik with for example cron jobs?

**Comment by FileGo** [comment]
Have a look at this: https://github.com/root-gg/plik/blob/master/server/plikd.cfg

**Comment by hvisage** [comment]
Having the same question, but the answer is the SERVER config, while I'm also in need of the CLIENT config template/manual/documentation ;(

**Comment by pieterhouwen** [comment]
If you run the client once there will be a default .plikrc file generated in the home directory which you can edit.

For reference:

```
Debug = false
Quiet = true
URL = "https://plik.root.gg"
OneShot = true
Removable = false
Stream = false
Secure = false
SecureMethod = "openssl"
Archive = false
ArchiveMethod = "tar"
DownloadBinary = "curl"
Comments = ""
Login = ""
Password = ""
TTL = 604800
AutoUpdate = false
Token = ""

[SecureOptions]
  Cipher = "aes-256-cbc"
  Openssl = "/usr/bin/openssl"
  Options = "-md sha256"

[ArchiveOptions]
  Compress = "gzip"
  Options = ""
  Tar = "/bin/tar"
```
