### ISSUE TITLE
cURL upload URL returned isn't right

### ISSUE THREAD

**Issue by emilevirus** [root-gg/plik#355]
When I upload a file using curl --form 'file=@bird.png' https://plik.domain/
it returns http://127.0.0.1/file/xxx/xxx/bird.png If I upload using webapp, the URL is OK.

**Comment by camathieu** [comment]
Hello Jacques,

You need to setup the server url in the server config file. Check the
Download Domain setting from the plik.cfg file

https://github.com/root-gg/plik/blob/master/server/plikd.cfg

There might be some room for improvement here to guess that url.
