### ISSUE TITLE
OTP for guest uploads

### ISSUE THREAD

**Issue by lzecca78** [root-gg/plik#356]
Hi! 
Thanks first of all for the amazing job! Is amazing and very easy to set up.
I was wondering that could be a very nice feature to be able to generate OTP to send to guest customers in order to allow them one-time upload. This could address a common issue where an external customer that doesn't belong to the internal company wants to send a file to the company.
Thanks in advance!

**Comment by camathieu** [comment]
Hello, it's already possible.

Just create an empty upload and send him the upload admin url (with the
upload token)

**Comment by lzecca78** [comment]
yep is true, but unfortunately, the upload admin url, is a query string from the root URL and (AFAIK) is not possible to filter exception in a webserver with query strings.

**Comment by camathieu** [comment]
You could setup a redirection using a reverse proxy maybe ?
