### ISSUE TITLE
Feature request: pasting content from clipboard

### ISSUE THREAD

**Issue by MairusuPawa** [root-gg/plik#362]
Hello!

One feature I usually enjoy in file-sharing tools is the ability to directly paste your clipboard's content, when it's a picture. This makes sharing screenshots especially easy, without any need to save a temporary file on the local machine.

Could Plik support something similar? Thanks,

**Comment by brabiega** [comment]
Same goes for text pastes!

**Comment by camathieu** [comment]
This would be indeed some very nice features.

The project is not super active those days but if you'd like to contribute
I'll be pleased to help, review and merge.

Cheers CAM.
