### ISSUE TITLE
Repository from mir.root.gg

### ISSUE THREAD

**Issue by tete2soja** [root-gg/plik#376]
Hello,

I wanted to use the repository but it seems to be offline. I used the tar method instead but repository is easier to use to perform update.
Any chances to be back online ?

Thanks for this tool!

**Comment by camathieu** [comment]
Unfortunately we don't plan to support mir.root.gg anymore.
I've updated the REAME.md accordingly.

https://github.com/root-gg/plik/commit/bb1a7016c26f2eb123768009c92040c4953638da

Sorry for the inconvenience.

**Comment by tete2soja** [comment]
Thanks for the information!
