### ISSUE TITLE
Security: Pasted password will be displayed in plain text in the "Pasted Text" dialogue

### ISSUE THREAD

**Issue by adan89lion** [root-gg/plik#392]
**Bug Description**
Starting from 1.3.4 Release, users are able to share texts directly by pasting the text in the browser. However, I tried to log into my account in Plik, pasting my password from my password manager will cause the "Pasted Text" dialogue to appear. Sadly, the password will be displayed to the public in **plain text** form, which is a possible security breach.

**Steps to reproduce**
- Navigate to self-hosted Plik instance
- Click ``Authenticate`` and paste my password from password manager.
- The password is correctly pasted into the password field, but also the "Pasted Text" dialogue in **plain text**.

**Specs**
Device Tested: ``iPad Pro 12.9" 2021``
Browser and OS: ``Safari in iPadOS 15.2 (Build 19C56)``

**Notes**
It also happens when pasting to _any_ text field, like password protection for each files, or even expiry date field.

**Comment by camathieu** [comment]
Good catch thank you for the report.
Will work a fix asap.

**Comment by camathieu** [comment]
I see two issues :

- When you open the main page then switch to another like login/home/admin/... the paste handler is not removed
- When you are on the main page the paste handler works even if another dialog (especially upload password) is already open
