### ISSUE TITLE
Readme.MD contains error in text

### ISSUE THREAD

**Issue by ClumsyNavigator** [root-gg/plik#395]
Readme.MD contains below:
$ wget https://github.com/root-gg/plik/releases/download/1.3.4/plik-1.3.4-linux-amd64.tar.gz
$ tar xzvf plik-1.3.4-linux-64bits.tar.gz
$ cd plik-1.3.4/server
$ ./plikd

But should contain:
$ wget https://github.com/root-gg/plik/releases/download/1.3.4/plik-1.3.4-linux-amd64.tar.gz
$ tar xzvf plik-1.3.4-linux-amd64.tar.gz
$ cd plik-1.3.4-amd64/server
$ ./plikd

Source: https://github.com/root-gg/plik#from-release

**Comment by camathieu** [comment]
Good catch thank you for the heads up.

Fixed in : https://github.com/root-gg/plik/commit/b6045500edea7b7a27b0a411936c4250feeca854
