### ISSUE TITLE
rootgg/plik-linux-arm ist not ARM?

### ISSUE THREAD

**Issue by brainnex** [root-gg/plik#401]
Hello, 
I just installed Plik from rootgg/plik-linux-arm on a RaspberryPi 4 but it seems not to be an ARM Build. The Container does not start:
`standard_init_linux.go:228: exec user process caused: exec format error`

`pi@raspberrypi:~/Docker $ docker inspect sha256:60df858a65529c00e4bda4471dd70df93b5ed1e29d60ef1087fee6a3ab538c35 | grep Architecture
        "Architecture": "amd64",
`
For me it looks like still be amd64 and not arm.
Thank you for your work.

**Comment by camathieu** [comment]
I've rerun the release job for 1.3.4 :

The following images seem to have the right binary format :
- rootgg/plik-linux-arm:latest
- rootgg/plik-linux-arm:1.3.4

```
🪂 ➜  plik git:(a460294) ✗ docker pull rootgg/plik-linux-arm:latest
latest: Pulling from rootgg/plik-linux-arm
Digest: sha256:d749fb5fddcf8f9a70c07538e97f46512f7b9813253e53fe54d47f48f7ccd143
Status: Image is up to date for rootgg/plik-linux-arm:latest
docker.io/rootgg/plik-linux-arm:latest
🪂 ➜  plik git:(a460294) ✗ docker create rootgg/plik-linux-arm:latest
b18b9a9b9d7c3b9a720c900cbd0fc3c92fee33f81eac442dccc0eccd8c34dc92
🪂 ➜  plik git:(a460294) ✗ docker export b18b9a9b9d7c3b9a720c900cbd0fc3c92fee33f81eac442dccc0eccd8c34dc92 > image.tar 
🪂 ➜  plik git:(a460294) ✗ mkdir image
🪂 ➜  plik git:(a460294) ✗ tar -xf image.tar --directory image
🪂 ➜  plik git:(a460294) ✗ file image/home/plik/server/plikd
image/home/plik/server/plikd: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, for GNU/Linux 3.2.0, Go BuildID=UFoeIvANdxJbT_Bv7B0E/6gVZHU9PG1oSJhe3-rZ5/JCfijbVeApE3u7bOYUJE/hfbppRNdvDAuJpRB-E1L, BuildID[sha1]=db1b32dc267ef170cee548fd646ec26b1d4052e9, stripped
```

We don't do multiarch docker images yet. The Architecture in docker inspect is indeed always amd64 but I don't think that it should not be an issue to start the container.

If still no success could you try to download and run the 1.3.4 arm release [plik-1.3.4-linux-arm.tar.gz](https://github.com/root-gg/plik/releases/download/1.3.4/plik-1.3.4-linux-arm.tar.gz) ?

**Comment by camathieu** [comment]
Maybe you need some specific ARM build for hardware floating point build for example See : https://github.com/golang/go/wiki/GoArm

```
GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc make server
server/plikd: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, for GNU/Linux 3
```

**Comment by brainnex** [comment]
> The following images seem to have the right binary format :
> 
>     * rootgg/plik-linux-arm:latest
> 
>     * rootgg/plik-linux-arm:1.3.4

i still have no luck with this. Same error on starting container. The raspberry pi 4 has a Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz CPU. 

Im still running old 32Bit Raspbian:

pi@raspberrypi:~/Docker $ lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500,0000
CPU min MHz:         600,0000
BogoMIPS:            108.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32

Im running several other container on my pi but all are armv7. Maybe we are talking about different arm versions. I thought plik-linux-arm is suitable for pi armv7.

**Comment by camathieu** [comment]
I'll take a look at how the the manifests works and use docker buildx to fix the Docker image arch format.

**Comment by camathieu** [comment]
Could you try running rootgg/plik.multiarch:dev ?

https://hub.docker.com/repository/registry-1.docker.io/rootgg/plik.multiarch/tags?page=1&ordering=last_updated

**Comment by brainnex** [comment]
Yes!! Container is starting up and running! This seems to be the write way. A clean multiarch docker hub would be a nice feature. Thank you for your help.
