### ISSUE TITLE
Hardcoded /bin/bash path breaks installation on FreeBSD

### ISSUE THREAD

**Issue by Cubox** [root-gg/plik#404]
/bin/bash doesn't exist on FreeBSD

**Comment by camathieu** [comment]
I guess the issue is when running `make`
Would `/bin/sh` be ok ?

I'll check if we can switch the [makefile ](https://github.com/root-gg/plik/blob/28c21aa499110b70a3af4bc649a1c4f4abe3d9da/Makefile#L1) to /bin/sh.

**Comment by Cubox** [comment]
The makefile is fine, but [the releaser.sh](https://github.com/root-gg/plik/blob/master/releaser/releaser.sh) script uses some [[ that sh doesn't have.
_Also_, you use make in that script, which is replaced by gmake on freebsd, but that's much more difficult to accommodate.
Given that there are still many steps to get it to compile on FreeBSD, I would understand if you don't want to bother with supporting it.

**Comment by Cubox** [comment]
Yeah, you need to replace all hardcoded paths to bash to something else (/usr/local/bin/bash for a quick edit)
Then you replace all calls to make to gmake
Then you replace the call of tar that uses --transform to gtar

**Comment by camathieu** [comment]
I'm not sure to fully understand the issue with make/gmake on FreeBSD but making Plik more portable would be nice.

The problematic step seems to "make clients" that calls the releaser.sh to make clients for all architectures. Could you confirm that "make frontend" and "make server" works. 

For make clients we could come back to the previous implementation of the [Makefile](https://github.com/root-gg/plik/blob/2d15cbec52716ac5087cef4aa4c668ca42b7f444/Makefile#L72).

We try to use Docker more and more to build to avoid to have to setup build environment every time. The releaser.sh script is meant to be called by the Dockerfile as part of the multiarch image build and release process. So if you have docker available on your freebsd environement then maybe this is currently the easiest way to build.
```
    docker buildx build --progress=plain --target plik-release-archive -o releases .
```
