### ISSUE TITLE
Pasting files on firefox is broken

### ISSUE THREAD

**Issue by Cubox** [root-gg/plik#405]
Tried on Firefox 97.0b8, on a new profile.
I can only paste an image when clicked in this zone:
![image](https://user-images.githubusercontent.com/479129/151356156-a884dea5-cf96-4c83-b4ec-b58fd1e1efd5.png)
Since clicking on the middle zone will open a file explorer, you can only use the little bit of space on the left of the field to make it work. Pasting after clicking anywhere else won't do anything.

However, if you paste text, it works everywhere in the page. I'm happy to do any testing/edits to try fixes and find a solution.

**Comment by Cubox** [comment]
I tried to follow the JS to see if there was any difference between the behaviour when it works and when it doesn't, and I couldn't see anything

**Comment by camathieu** [comment]
Hello, thank you for the report, I was able to reproduce.
I'll take a look myself too.

**Comment by camathieu** [comment]
https://github.com/root-gg/plik/commit/8a6b703ca27f857c2da0b928551e67c93c73a186

Making a defensive copy of the file array seems to fix the image pasting issue in firefox.

**Comment by camathieu** [comment]
However pasting files still doesn't work but it's not the same issue they do not appear in the clipboard data.

**Comment by camathieu** [comment]
I'll also patch to be able to paste multiple images without having to rename the files manually.

**Comment by Cubox** [comment]
I can confirm image pasting on Firefox has been fixed with this commit.
Thanks
