### ISSUE TITLE
Disable paste feature when asking password

### ISSUE THREAD

**Issue by pbe-axelor** [root-gg/plik#406]
Hi,

For upload protected by a password, it prompt a dialog before the upload. The recently added paste feature is still active. So instead of pasting data in the password input (suppose we copy a temp password from a password generator), it tries to create a new upload (on a new dialog) instead of just paste the password in the form input.
I think the paste feature should be disable when it shows the dialog, allowing to paste a password in the form input.

Thx!

**Comment by camathieu** [comment]
Hello,

Thanks for the report. 
This issue has been reported in 1.3.4 (#392) and it should be fixed in 1.3.5. Can you confirm ?

Best,
Cam.

**Comment by pbe-axelor** [comment]
My bad. That's right, it is fixed on 1.3.5.
I just upgraded from 1.3.4, but I didn't refresh/clear cache, so I guess I was still on old version.

Thx
