### ISSUE TITLE
Request: Admin panel should list all files

### ISSUE THREAD

**Issue by Cubox** [root-gg/plik#411]
The admin panel should list all the uploads, and give an option for the admin(s) to delete uploads, access them and maybe edit them

**Comment by camathieu** [comment]
Indeed, that's a good feature candidate for next release.

It's possible to list all files from the server CLI.

```
./plikd file list
XD2cDJEKGFJirjg8p YyOOEkrjsiekdjnh 725 MB uploaded application/octet-stream IMG_6111.MOV
QkejgiDJendG2beB igQKKGEOGkeodUD 4.8 GB uploaded application/octet-stream 19.3.7z
Q3JEGIkejskeedbeB vsMIKKEGlrosjedgG 5.0 GB uploaded application/octet-stream 19.2.7z
```

Admins are able to access / edit all uploads (given they have the ID).

**Comment by camathieu** [comment]
https://github.com/root-gg/plik/commit/67a85894045d5b4414757b2a68b42cddb6bd8797
