### ISSUE TITLE
Request: Don't let an admin impersonate themselves

### ISSUE THREAD

**Issue by Cubox** [root-gg/plik#413]
I'm not even sure what impersonating someone does, but being able to impersonate yourself seems like it shouldn't work

**Comment by camathieu** [comment]
Impersonate let admins browse Plik as another user. It allow to list user uploads/tokens and delete them.
Impersonating yourself is harmless/useless, we'll disable the button.

**Comment by camathieu** [comment]
Fixed in https://github.com/root-gg/plik/commit/c3891cacbd6ceba209b1e16b03680095e821d82a

**Comment by camathieu** [comment]
Released in https://github.com/root-gg/plik/releases/tag/1.3.6
