### ISSUE TITLE
Uploads are really slow on Firefox

### ISSUE THREAD

**Issue by lucas1sanz** [root-gg/plik#419]
Hello,

I have been testing Plik and have noticed that uploading files through Firefox takes 4 times more than on other browsers. I have tested this with Chrome, Safari, Opera and Firefox.

For example a 1Gb file took 28.679544989s. On Firefox it took 2m17.199512934s.

This is most likely a Firefox issue, but I would like you to know so maybe you can point me to what the issue is or can warn users about it.

If you need any more info, do not hesitate to contact me.

Thanks!

**Comment by camathieu** [comment]
Hello, thanks you for the bug report, I'll take a look asap.

**Comment by camathieu** [comment]
Maybe related to : https://bugzilla.mozilla.org/show_bug.cgi?id=1596576
