### ISSUE TITLE
Always horizontal scroll bar on page

### ISSUE THREAD

**Issue by ClumsyNavigator** [root-gg/plik#435]
No matter the resolution you have in the browser, when Plik is deployed from a container there is always a horizontal scroll bar in the screen. This will scroll between text but the background will stay in place.

**Comment by camathieu** [comment]
Hello, which version are you using ?

**Comment by ClumsyNavigator** [comment]
Hi, I'm using the latest container version

**Comment by camathieu** [comment]
This should have been fixed in : https://github.com/root-gg/plik/commit/92c7d2527dae8a701d5c22f988528db6e8c41eb2.

Could you confirm please confirm that the bug is also present on https://plik.root.gg (without cache) ?
Maybe a screenshoot could also help.

**Comment by ClumsyNavigator** [comment]
Hi,

Thanks for checking this.
I do see that on https://plik.root.gg it is no longer present.

In my instance, running the docker container, it seems to still be present.
I do have a custom wallpaper there with the size of 1920x1080, could this be the cause here maybe?

See below screenshot:
![image](https://user-images.githubusercontent.com/93208828/168773616-0265c3d4-709d-4c5e-ab55-7a4bd55f9af8.png)

**Comment by camathieu** [comment]
Released in https://github.com/root-gg/plik/releases/tag/1.3.6
