### ISSUE TITLE
Ability to automatically put password option on True

### ISSUE THREAD

**Issue by ClumsyNavigator** [root-gg/plik#436]
I'm looking to automatically put the password option for downloads on On.
If possible even to disable to turn this off.

Is this a possibility?

**Comment by camathieu** [comment]
https://github.com/root-gg/plik/issues/264

**Comment by camathieu** [comment]
This has been addressed in https://github.com/root-gg/plik/pull/434

You'll be able to use the following in plikd.cfg in the next release :
`FeaturePassword       = "forced"`

**Comment by camathieu** [comment]
Released in https://github.com/root-gg/plik/releases/tag/1.3.6

**Comment by ClumsyNavigator** [comment]
I can tell you it works like a charm! Thanks!
