### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by guillaumesoucy94** [root-gg/plik#438]
This is not an issue, I just want to know how to update to it's latest version? I can't find anything here about that.

Thanks,

Guillaume

**Comment by camathieu** [comment]
Feel free to reopen or to contact us on Telegram : https://t.me/plik_rootgg

**Comment by guillaumesoucy94** [comment]
Hello, 

I deeply apologies for the delays. 

 I'd deployed Plik using the binary. I'm upgrading from 1.3.1 (Oct 27th 2020).

Thank-you!

Guillaume

**Comment by guillaumesoucy94** [comment]
Hello, 

I also send you a message on Telegram. 

Thank-you, 

Guillaume

**Comment by camathieu** [comment]
Hi, the safest way to do so is to backup the database and upgrade directly to the last release. Are you facing any error ?

**Comment by camathieu** [comment]
Hello,

The safest way to go is to backup the database and upgrade the release to the last version.

Are you facing any error ?
