### ISSUE TITLE
Plik seems to fail setting the correct headers

### ISSUE THREAD

**Issue by artemislena** [root-gg/plik#445]
fc17: Our instance (https://plik.artemislena.eu) keeps throwing CORS errors (and not working), due to missing headers, perhaps… and enabling EnhancedWebSecurity doesn't seem to do anything header-wise, i.e. none of the described ones are set, according to `curl`…

**Comment by camathieu** [comment]
Hello,

I've not played with EnhancedWebSecurity since quite a while I'll give it a
freag go. We should try to makes things work without it at first.

I don't get why you would get CORS issues at all unless the Plik server API
is on a different domain than the UI, is that your case ?

**Comment by artemislena** [comment]
Oh… it's behind a reverse proxy… does the Host header matter, or something like that?

**Comment by camathieu** [comment]
To me as long as the static content is served on the same domain than the
API there should be no cross domain request occurring hence no CORS issue.
I'll take a look at your instance.

**Comment by artemislena** [comment]
It definitely has to do something with the reverse proxy… it works if accessing it directly; through the LAN address…
