### ISSUE TITLE
critical error when enabling encryption on s3 storage backend

### ISSUE THREAD

**Issue by oupala** [root-gg/plik#455]
I have a critical error when uploading a simple image file :

> [09/14/2022 10:21:40][CRITICAL][[10.129.2.1][uMAlAUTgO2ZPUnhr][IMG_20220907_085611.jpg]] unable to save file : A header you provided implies functionality that is not implemented. --  -- 500

The only thing that I have added to the configuration of plik is the S3 encryption settings:

> SSE-C: server-side-encryption with customer provided keys ( managed by Plik )

```ini
[DataBackendConfig]
    SSE = "SSE-C"
```

I don't think I have a specific header provided...

What are the "customer provided key" that the documentation is talking about?

**Comment by camathieu** [comment]
Hello,

What kind of S3 backend are you trying to use ?

Best,
CAM.

**Comment by oupala** [comment]
I'm using an internal hosted S3 storage solution based on [scality](https://www.scality.com/).

**Comment by oupala** [comment]
I don't understand why the encryption would fail. As the encryption is "managed by plik", it should work natively on the same S3 hosting solution whenever the encryption is enabled or not! Am I right?

**Comment by camathieu** [comment]
Hi, what error are you facing ?

**Comment by oupala** [comment]
The error is mentioned in the first post of the thread.

**Comment by camathieu** [comment]
Sorry I replied from my phone which didn't have the thread history.

**Comment by camathieu** [comment]
I think this has to do with your backend not implementing the feature. 
With SSE-C the encryption is managed by the S3 backend with only the encryption keys being managed by Plik. The documentation string could be improved in this regard.

More details here : https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html

**Comment by oupala** [comment]
You're right, the backend does not support standard encryption. scality only offera custom encryption feature.

I think that the documentation string could be improved as I was understanding the encryption was managed by Plik (and there was therefor no impact or requirement on the S3 service). In fact, the encryption is always managed by the S3 service, the difference between SSE-C en standard S3 is only the question of who is managing the encryption keys.
