### ISSUE TITLE
streaming to multiple clients

### ISSUE THREAD

**Issue by oupala** [root-gg/plik#456]
Is it possible with plik to stream a file to multiple clients? If yes, I did not manage to do this...

This could be useful when trying to distribute a file to all attendees of a training.

**Comment by camathieu** [comment]
It is by design impossible to achieve this.
The best is to upload the file and to delete it once everybody downloaded
the file.

**Comment by oupala** [comment]
You say it is impossible, but it appears that another tool is achieving this: [Just drop it](https://github.com/Orange-OpenSource/just-drop-it).

You can have a look at the third screenshot and see that the file is currently being distributed to two clients.

Is there any particular (design?) reason that make multiple streaming impossible to achieve for Plik, but possible for Just drop it?

**Comment by camathieu** [comment]
The current client / server architecture is not designed to achieve this
without heavy modifications. It would need to be able to upload the same
file several times in parallel and to serve it under the same URL.

**Comment by oupala** [comment]
I think that this is the way Just drop it is working when streaming file to multiple clients: opening one websocket per client:

![schema](https://user-images.githubusercontent.com/13458743/190354116-9f902b93-5d54-4f37-84d1-4e895c0be33a.svg)

I note that plik is currently designed for one to one stream transfer.

**Comment by camathieu** [comment]
There is no websocket involved. The content of the upload request body is piped directly to the download response body without any buffering

**Comment by camathieu** [comment]
For streaming to multiple clients maybe you can look at torrent protocols

**Comment by m2acgi** [comment]
piping-server support stream to multiple client: https://github.com/nwtgck/piping-server#transfer-to-multiple-receivers
