### ISSUE TITLE
Folders not being deleted

### ISSUE THREAD

**Issue by pieterhouwen** [root-gg/plik#463]
Hello,

When the system is purging old uploads it removes the files themselves but not the containing folder resulting in many many empty folders in the ```files``` directory.

How can this be fixed? 

I can cd into the ```files``` directory and do a ```rmdir *``` so it will keep all the folders containing files but a better solution would be that the system does that for me :)

**Comment by camathieu** [comment]
Taking a look

**Comment by camathieu** [comment]
https://github.com/root-gg/plik/pull/477
