### ISSUE TITLE
Oops ! (413) Error.

### ISSUE THREAD

**Issue by guillaumesoucy94** [root-gg/plik#464]
Hello, 

I'm not able to upload files larger than 2GB and 700MB files fails due to a timeout. 

![20230116-054817](https://user-images.githubusercontent.com/22561876/212661838-413ad418-c180-4fd2-9407-6e3a4d894984.jpg)

How to increase the upload file size ans increase the execution time?

Plik is behind Nginx Proxy Manager. 

Thank-you, 

Guillaume

**Comment by bodji** [comment]
Probably due to nginx buffering.

Can you modify the config file ? 

If yes, you can add these lines : 

```
proxy_buffering off;
proxy_request_buffering off;
proxy_http_version 1.1;
proxy_buffer_size 1M;
proxy_buffers 8 1M;
client_body_buffer_size 1M;
```

**Comment by camathieu** [comment]
Feel free to reopen

**Comment by kerenon** [comment]
For anyone running into the same issue:
Just add "client_max_body_size 5000M;" on the advanced tab as custom nginx configuration. You can replace "5000M" to any size you require. This allows files up to 5GB.
