### ISSUE TITLE
no more abuse contact in footer

### ISSUE THREAD

**Issue by oupala** [root-gg/plik#466]
I can't see any abuse contact email in the footer of https://plik.root.gg/:

```html
<footer class="footer ng-scope" ng-controller="MenuCtrl">
    <!-- ngIf: config.abuseContact -->
</footer>
```

I think that there is a problem...

**Comment by camathieu** [comment]
Hello, 

We never configured an abuse contact for https://plik.root.gg.
I configured one and it worked so I'm not sure about the issue here.

**Comment by oupala** [comment]
Ok, I thought the abuse contact email was indeed for plik.root.gg

So, my assumptions were wrong. Nevermind.
