### ISSUE TITLE
Can only create one local user

### ISSUE THREAD

**Issue by Ronaldr1985** [root-gg/plik#468]
Can successfully create a local admin user using the command
`plikd --config /etc/plikd.cfg --login root user create --name Admin --provider local`
However, if I then try to create another user with
`plikd --config /etc/plikd.cfg --login root user create --name ronaldr1985 --provider local`
then I get
`User already exists`
Even after verifying that the user doesn't exist with
`plikd --config /etc/plikd.cfg --login root user list`

**Comment by e0xify** [comment]
Your Login is --login root for both users

Login: loginname
Name: displayname (not login)

you are using the same login twice which is root so its duplicate

**Comment by Ronaldr1985** [comment]
Apologies, I didn't realise that is what login meant.  Might be worth changing the help to read something like:
`--login is the login name for the user`
Just to make it more clear.  Feel free to close the issue.
