### ISSUE TITLE
rootless Docker image

### ISSUE THREAD

**Issue by oupala** [root-gg/plik#474]
plik Docker image currentyl require to be executed as root.

The following change allow the image to be run as non root.

```Dockerfile
FROM dockerproxy.repos.tech.orange/rootgg/plik:1.3.6

USER root

RUN addgroup plik root

RUN chgrp -R root /home/plik \
 && chmod -R g+ws /home/plik

USER plik
```

If this could be embedded inside the official plik Docker image, this would make it much more portable!

**Comment by camathieu** [comment]
Plik docker is not intended to be run as root.

**Comment by oupala** [comment]
Thank you!
