### ISSUE TITLE
S3 file won't be deleted

### ISSUE THREAD

**Issue by yellowsoar** [root-gg/plik#481]
## Briefing
The S3 file won't be deleted after removing them from Plik web UI. Is that the default or a bug?

## Env
container image:"rootgg/plik:1.3.6"

## Some test
- The token & secrete I used in the container runtime did remove the objects with the following AWS CLI.
`aws s3api delete-object --bucket {bucket_name} --key {object_name}`

**Comment by camathieu** [comment]
The actual file deletion is an asynchronous background process that runs
every few hours. You can manually trigger it by running

. /plikd clean

Did that log any error ?

CAM

**Comment by yellowsoar** [comment]
> The actual file deletion is an asynchronous background process that runs every few hours.

Nice, I thought it's removed immediately. I checked the S3 bucket a few hours later, the files are deleted correctly.
