### ISSUE TITLE
plikd create user --password broken, password not set when provided

### ISSUE THREAD

**Issue by aschils** [root-gg/plik#489]
Hello,

Just quickly reporting what I think might be an easy to fix bug with the create user feature.
When creating a user and when providing explicitly his password, plikd reports that the password is too short (even if the provided password is very long).

I think the issue is simply that the user password is set only when generated automatically. I have attached a screenshot with my git diff. I tried to submit pull request through github website after forking but apparently it didn't go through for some reason.

![image](https://github.com/root-gg/plik/assets/5392362/df9dd9bd-e703-4440-8c41-0bca05d423ea)

Regards.

**Comment by camathieu** [comment]
Hi, many thanks for the bug report, we'll fix that for next release that
should happen right after we come back from vacation. We'll keep you
posted.

**Comment by paulkitt** [comment]
Heyhey,
the latest docker image still facing this problem.
Maybe rebuild current master could fix this issue?
Thanks

**Comment by camathieu** [comment]
1.3.8 will be released today.

**Comment by stefanmm** [comment]
I have the same issue on the latest Docker image.
The fix was simple: remove special characters from the password.
I managed to add some ! and * characters in the middle of the password.
Be sure not to place special characters at the beginning.
