### ISSUE TITLE
Add configurable limit for total max size

### ISSUE THREAD

**Issue by axedoardo** [root-gg/plik#495]
Right now in the config file you can set the max dimension of a single file with MaxFileSizeStr.
It would be useful to add a total maximum size limit, useful for example when you upload a lot of small files and you want to limit the total size.

**Comment by camathieu** [comment]
Hi, you are lucky :)

This as been implemented and will be part of the next release probably
next week. You can try it by building from sources on master or with docker
rootgg/plik:dev
