### ISSUE TITLE
Config url with trailing / fail

### ISSUE THREAD

**Issue by cyrbil** [root-gg/plik#85]
When adding an url like `https://plik.root.gg/`  
the trailing `/` make it fail (redirection)

Validating inputed url with https://golang.org/pkg/net/url/#Parse would also be nice :)

**Comment by bodji** [comment]
Working for me.

$ plik README.md 
Please enter your plik domain [default:http://127.0.0.1:8080] : https://plik.root.gg/
Do you want to enable client auto update ? [Y/n] y
Plik client settings successfully saved to /home/mbodjiki/.plikrc
Upload successfully created : 
    https://plik.root.gg//#/?id=Kq04m97icnKrdDIb

**Comment by bodji** [comment]
But ok for validate url, I'll put that for 1.1

**Comment by camathieu** [comment]
We should also strip the trailing slash to get a better download url display

**Comment by bodji** [comment]
All good. 
I close
